### ISSUE TITLE
Port 502

### ISSUE THREAD

**Issue by double-ee** [tim-hellhake/modbus-bridge#1]
The adapter defaults to port 42337.  When I try to change it to port 502, it fails.  These are the log entries I see when this happens:

2021-01-25 12:45:59.497 INFO   : modbus-bridge: Starting modbus tcp server
2021-01-25 12:45:59.512 ERROR  : modbus-bridge: events.js:174
2021-01-25 12:45:59.526 ERROR  : modbus-bridge:       throw er; // Unhandled 'error' event
2021-01-25 12:45:59.527 ERROR  : modbus-bridge:       ^
2021-01-25 12:45:59.528 ERROR  : modbus-bridge: 
2021-01-25 12:45:59.529 ERROR  : modbus-bridge: Error: listen EACCES: permission denied 0.0.0.0:502
2021-01-25 12:45:59.530 ERROR  : modbus-bridge:     at Server.setupListenHandle [as _listen2] (net.js:1263:19)
2021-01-25 12:45:59.531 ERROR  : modbus-bridge:     at listenInCluster (net.js:1328:12)
2021-01-25 12:45:59.533 ERROR  : modbus-bridge:     at doListen (net.js:1461:7)
2021-01-25 12:45:59.534 ERROR  : modbus-bridge:     at process._tickCallback (internal/process/next_tick.js:63:19)
2021-01-25 12:45:59.537 ERROR  : modbus-bridge: Emitted 'error' event at:
2021-01-25 12:45:59.539 ERROR  : modbus-bridge:     at emitErrorNT (net.js:1307:8)
2021-01-25 12:45:59.540 ERROR  : modbus-bridge:     at process._tickCallback (internal/process/next_tick.js:63:19)  

It's also not able to read bits.  I've tried reading them as coils (function code 1) and discrete inputs (function code 2).

**Comment by tim-hellhake** [comment]
You need root privileges to bind ports below 1024.
If you really need to use port `502` you can forward the traffic to port 42337 using iptables.

**Comment by tim-hellhake** [comment]
> It's also not able to read bits. I've tried reading them as coils (function code 1) and discrete inputs (function code 2).

Are there any errors in the logs?
You can find them at `https://[your gateway]/settings/developer` under `View Internal Logs`.

**Comment by double-ee** [comment]
I was able to NAT the traffic from 502 to 42337, it took a while to learn iptables but it's working now.  I'm using WireShark to troubleshoot the discrete communications.  I can see the queries from my Modbus simulator, and an exception returned from the gateway that says "Exception Code: Slave device failure (4)."  I don't see any entries in the internal logs associated with this.

**Comment by tim-hellhake** [comment]
@double-ee
I think I finally found the issue.
Sorry for the delay.
I'll submit a new update in a few minutes so you can test it.

**Comment by double-ee** [comment]
@tim-hellhake 
I've tested a little bit using a Modbus emulator and it looks like the add-in allows everything to be read through the Modbus connection.
